# Global settings applied to the whole site.
#
# "publish" is the directory to publish (relative to root of your repo),
# "command" is your build command,
# "base" is directory to change to before starting build. if you set base:
#    that is where we will look for package.json/.nvmrc/etc not repo root!

[build]
  publish = "docs/packages"
  command = "npm install --ignore-scripts && cd packages/ui-predicate-core && npm install --ignore-scripts && npm run build && npm run docs:build && cd ../ui-predicate-vue3 && npm install && npm run build && npm run docs:build && cd ../.. && node scripts/docs-build-index.js"

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.11"
