name: build-test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: cd packages/ui-predicate-core && npm install --ignore-scripts
      - run: cd packages/ui-predicate-core && npm run lint
      - run: cd packages/ui-predicate-core && npm test
      - uses: codecov/codecov-action@v4
        with:
          functionalities: gcov

  vue3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: cd packages/ui-predicate-vue3 && npm install
      - run: cd packages/ui-predicate-vue3 && npm run lint
      - run: cd packages/ui-predicate-vue3 && npm run build
      - run: cd packages/ui-predicate-vue3 && npx vitest run
