name: build-test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '11'
      - run: npm install
      - run: npm run postinstall
      - run: npm run lint
      - run: npm run libs:build
      - run: npm run docs:build
      - run: npm run test:coverage
      - uses: codecov/codecov-action@v1.5.2
        with:
          functionalities: gcov # disable gcov
